# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=80, null=True)),
                ('NewRow', models.BooleanField(default=False)),
                ('Width', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=80, null=True)),
                ('Drop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=80, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='Spots',
            field=models.ManyToManyField(to='cards.Spot'),
        ),
        migrations.AddField(
            model_name='row',
            name='Visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Visibility'),
        ),
        migrations.AddField(
            model_name='game',
            name='Rows',
            field=models.ManyToManyField(to='cards.Row'),
        ),
    ]
