# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='Game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.Game'),
            preserve_default=False,
        ),
    ]
